### ISSUE TITLE
Different URL for Bookland

### ISSUE THREAD

**Issue by thefloatman** [lenalebt/obsidian-pocketbook-cloud-highlight-importer#1]
**Descriptions**

When Testing this plugin, I got this error
`Uncaught (in promise) Error: Could not log in to Pocketbook Cloud`
![2023-05-15_09-44](https://github.com/lenalebt/obsidian-pocketbook-cloud-highlight-importer/assets/54065187/eb0173fe-2f79-432c-9d37-8b9fef86e79c)

Tried to debug it and found that "Bookland" using different url for login
`https://cloud.pocketbook.digital/api/v1.0/auth/login/bookland` instead of `https://cloud.pocketbook.digital/api/v1.0/auth/login/knv`

response from knv:
`{
    "error_code": 1207,
    "error_msg": "Authorization partner user failed"
}`

**Dataview Version**
0.5.55

**Obsidian Version**
Version 1.2.7 (Installer 1.1.16)

**OS**
Mac OS

**Comment by lenalebt** [comment]
Hey,
thanks for your report! I have two shops in my account and they both used `knv`. I made an adjustment that should fix it for you. It would be great if you test it and report back :-). I'll release it as an updated version in a few minutes.

Cheers,
Lena

**Comment by thefloatman** [comment]
Hi Lena

Nice it's working, 
but unfortunately still getting errors when syncing the highlights (some of my books don't have highlights)
I can fix it directly on the console after adding safe navigations [here](https://github.com/lenalebt/obsidian-pocketbook-cloud-highlight-importer/blob/b37b2e90368f19ff68195170ec0d6dda36f87244/src/import.ts#L82) and [here](https://github.com/lenalebt/obsidian-pocketbook-cloud-highlight-importer/blob/b37b2e90368f19ff68195170ec0d6dda36f87244/src/import.ts#L100)
![2023-05-16_16-33](https://github.com/lenalebt/obsidian-pocketbook-cloud-highlight-importer/assets/54065187/d7537e68-50b2-400a-88c5-088c86980488)

**Comment by lenalebt** [comment]
Thanks for the hints :smile: . I fixed the issues and released 0.1.5, which should solve this as well. Can you test and report back?

**Comment by thefloatman** [comment]
@lenalebt Sorry for late reply its working now
Thank you
